# -*- coding: utf-8 -*-
"""English_to_French_and_Hindi(task3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCIdRb2i44OECn-o4ETPfQBv_jeWt3_C

**Translate only 10-letter English words and translate them into both French and Hindi at the same time.**
"""

!pip install gradio transformers torch sentencepiece

!pip install --upgrade gradio

import gradio as gr
from transformers import MarianMTModel, MarianTokenizer

model_name_fr = 'Helsinki-NLP/opus-mt-en-fr'
model_name_hi = 'Helsinki-NLP/opus-mt-en-hi'

try:
    tokenizer_fr = MarianTokenizer.from_pretrained(model_name_fr)
    model_fr = MarianMTModel.from_pretrained(model_name_fr)

    tokenizer_hi = MarianTokenizer.from_pretrained(model_name_hi)
    model_hi = MarianMTModel.from_pretrained(model_name_hi)

except Exception as e:
    print(f"Error loading models: {e}")

def translate_english_to_french_and_hindi(word):
    try:
        if len(word) == 10:

            inputs_fr = tokenizer_fr(word, return_tensors="pt", padding=True)
            translated_tokens_fr = model_fr.generate(**inputs_fr)
            french_translation = tokenizer_fr.decode(translated_tokens_fr[0], skip_special_tokens=True)


            inputs_hi = tokenizer_hi(word, return_tensors="pt", padding=True)
            translated_tokens_hi = model_hi.generate(**inputs_hi)
            hindi_translation = tokenizer_hi.decode(translated_tokens_hi[0], skip_special_tokens=True)

            return f"French: {french_translation}\nHindi: {hindi_translation}"
        else:
            return "This model only translates 10-letter English words."

    except Exception as e:
        return f"Error during translation: {e}"

def gradio_interface(word):
    result = translate_english_to_french_and_hindi(word)
    return result

interface = gr.Interface(
    fn=gradio_interface,
    inputs=gr.Textbox(lines=1, placeholder="Enter a 10-letter English word"),
    outputs="text",
    title="Translate English to French and Hindi",
    description="Enter a 10-letter English word and get its translation in French and Hindi.",
)


interface.launch()